## Nicer Config :) 

nominal_name: hA2018
target_name: noFSI

nominal_files: 
  /eos/project-n/neutrino-generators/generatorOutput/GENIE/DIRT_II_Studies/groundStateValidations/GENIE_3_04_00/AR23_20i_00_000_1000180400/flat_vec_AR23_20i_00_000_14_1000180400_3_04_00_6142.root #hA2018 FSI
target_files: 
  /eos/project-n/neutrino-generators/generatorOutput/GENIE/DIRT_II_Studies/groundStateValidations/GENIE_3_04_00/AR23_20n_00_000_1000180400/flat_vec_AR23_20n_00_000_14_1000180400_3_04_00_27504.root
number_of_train_events: 500000 # 5 out of 10M 
reweight_variables_names: 
  [Enu_true, CosLep, ELep, EavAlt, Erec_bias_abs, Erec_bias_rel]

bdt_ckpt_path: /data/rradev/reweighting/generator_reweight_bdt/trained_bdt
plots_path: /data/rradev/reweighting/generator_reweight_bdt/plots
